language: lisp

env:
  matrix:
    - LISP=sbcl LIBGIT2_VERSION=0.21.1
    - CIM_LISP=sbcl LIBGIT2_VERSION=0.21.2
    - CIM_LISP=sbcl LIBGIT2_VERSION=0.21.3
    - CIM_LISP=ccl LIBGIT2_VERSION=0.21.3
    - CIM_LISP=clisp LIBGIT2_VERSION=0.21.3
    - CIM_LISP=ecl LIBGIT2_VERSION=0.21.3

matrix:
 allow_failures:
   - env: CIM_LISP=clisp LIBGIT2_VERSION=0.21.3
   - env: CIM_LISP=ecl LIBGIT2_VERSION=0.21.3

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^#cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/russell/cl-travis/master/install.sh | sh;
    fi

  - sudo apt-get install libc6-dev-i386
  - wget --progress=dot https://github.com/libgit2/libgit2/archive/v${LIBGIT2_VERSION}.tar.gz
  - tar -zxf v${LIBGIT2_VERSION}.tar.gz
  - mkdir libgit-build
  - pushd libgit-build && cmake -DCMAKE_VERBOSE_MAKEFILE=ON ../libgit2-${LIBGIT2_VERSION} && popd
  - pushd libgit-build && cmake --build . && popd
  - pushd libgit-build && sudo cmake --build . --target install && popd

script:
  - LD_LIBRARY_PATH=/usr/local/lib cl --load run-tests.lisp
